CREATE DATABASE IF NOT EXISTS hearst_mark;
USE hearst_mark;

CREATE TABLE IF NOT EXISTS bookmarks (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  url VARCHAR(255) NOT NULL DEFAULT '0',
  name VARCHAR(256) NOT NULL DEFAULT '0',
  PRIMARY KEY (id),
  UNIQUE KEY url (url)
);